### PR TITLE
File redirection implemented

### PR DESCRIPTION
**Pull request by joeletho**
Hey there,

I found this library recently through a Reddit post, and thought I would try to contribute.

I have implemented a class to handle osmanip animation output redirection to a file. It's very simple to use, as you can see from the example file (and updated README.md). There are a few quirks, like having to flush the buffer on every loop iteration and it does not work well in a multi-threaded environment. But, other than that it's basically plug n play. 

I've included a basic test, with not check yet. However, the redirection example shows output redirection to both the console and the file before, during, and after the progress bar examples, except for the multi bars, and is a pretty good test in and of itself.

Let me know what you think.

Joel

### CODE REVIEW

**Comment by JustWhit3** [comment]
Hi @joeletho , sounds amazing! First of all **thank you very much** for the pull request with new features, really appreciated. I am ready to merge it, but before I have some questions / needings:

- Maybe you can (later) send another pull request with complete tests, also trivial tests for getters and setters are good for example, in order to maximize the tests coverage of the project. But I can do it on my own, if you prefer, when I have time.
- For the thread-safety problem, did you try to place an `std::mutex` lock into the main class members? This should be enough I think, but didn't tried yet. I can look at it too in any case.
- A bit of functions and methods documentation with Doxygen style is missing in the main new `.hpp` and `.cpp` files. See other source files as an example. It is better if you add it on your own since you wrote classes and methods and can help me better understand all the new features.
- Didn't understand what `scripts/setup.py` is supposed to do. I didn't implemented CMake compilation yet, but if you want to add it it would be a great thing (not necessarily with this pull request of course).
- Try to run the `tests/all_tests.sh` as a check, to see if all tests run correctly and anything has been broken for any reason. If possible update also the `tests/include_tests.sh` script. Sorry I think I forgot to mention it in the contribution file.

**Comment by joeletho** [comment]
I also forgot to mention that I'm using WSL2 on Windows 10 and I haven't tested any of this yet on another system.

**Comment by JustWhit3** [comment]
Thanks for the detailed explanation. It's clear that it hasn't been an easy work so this is a reason more to appreciate your updates!

Regarding your comments:

- This sounds awesome. So I think you can add the full tests in a new pull request and work on them without any hurry.
- Yeah it seems a bit complicated to implement it with few lines of code. I think this is not a priority stuff for the moment, even if thread-safety should be a good thing for this library, so also this can be done later with another pull request if necessary.
- Thanks, the documentation part is really important, expecially for me, so it would be better to put it within this pull request.
- Yeah, I think that for the moment removing `setup.py` (with this pull reuqest) is more than enough. If in future you want to implement a better building process with CMake (which is in my todo list) it would be really apprecciated.
- Thanks, also this can be done within the first item of this list.

I think that for the moment if you remove `setup.py` and update the documentation of source files it is enough and I can merge this pull request. Then, you can work on the remaining stuff with a new pull request, without any hurry. What do you think?

Thanks to you for your time!

PS: no need to test on other systems, I have workflows which test on Linux and MacOS and will add soon one for Windows, so don't worry for this task.

**Comment by joeletho** [comment]
Thanks! This has been a challenging project, but it's been a lot of fun and I've learned more about buffers than I ever wanted. 
I've made a merge to my main branch:
- I was able to knock out the documentation today and I also implemented thread safety for the ```OutputRedirector``` class, just in case. I hope the documentation is clear enough to understand what's going on.
- I also removed the ```setup.py``` from the project.
- The next task for me will be implementing some meaningful tests and the required documentation.

Let me know if anything needs attention.

**Comment by JustWhit3** [comment]
Sounds fantastic! Thank you very much for your updates, now the pull request is ready to be merged.

@all-contributors please add @joeletho for code

**Pull request merged**
