### PR TITLE
Redirection

### PR DESCRIPTION
**Pull request by joeletho**
Major update to ```OutputRedirector```, which includes the complete and correct use of ```OutputRedirector``` with all ```osmanip``` functions, including ```MultiProgressBar```, regardless of the number of threads. Addition of ```osm::iostream```, ```osm::Streambuf```, ```osm::Ostreambuf```, and a number of functions in ```strings.hpp/cpp``` that make handling ANSI CSI's possible.

Modifications to ```README.md``` to come.

### CODE REVIEW

**Comment by JustWhit3** [comment]
Hi @joeletho ,

Did you try reinstalling the library with all the new headers before running `all_tests`? This may causes include errors sometimes.

**Comment by joeletho** [comment]
That was it! I keep thinking that it's enough to just run ```make clean all```, instead of reinstalling the library as a whole. I'll try and remember that again for next time.

**Comment by JustWhit3** [comment]
Not sure, since include tests try to include using the absolute path with `<>`, so if the headers are not installed into the system it will cause an error.

**Comment by joeletho** [comment]
My pleasure!

**Pull request merged**
